import { Campsite } from "./types";

// 실제 API 키(GOCAMPING_API_KEY) 연결 전까지 사용하는 샘플 데이터입니다.
// 화면 구성과 동작을 확인하기 위한 것으로, 실제 캠핑장 정보와 다를 수 있습니다.
export const MOCK_CAMPSITES: Campsite[] = [
  {
    id: "mock-1",
    name: "강촌 숲속 캠핑장",
    address: "강원특별자치도 춘천시 강촌로 123",
    lat: 37.7975,
    lng: 127.6564,
    image: "https://picsum.photos/seed/camp1/800/500",
    intro: "북한강을 끼고 있는 숲속 캠핑장. 데크사이트와 파쇄석사이트를 함께 운영합니다.",
    facilities: ["전기", "온수 샤워장", "개수대", "매점", "무선인터넷"],
    tel: "033-000-0001",
    homepage: "https://www.gocamping.or.kr",
    type: "일반야영장",
    region: "강원",
  },
  {
    id: "mock-2",
    name: "가평 강변 오토캠핑장",
    address: "경기도 가평군 청평면 강변로 45",
    lat: 37.7333,
    lng: 127.3667,
    image: "https://picsum.photos/seed/camp2/800/500",
    intro: "차량을 사이트 옆에 바로 댈 수 있는 오토캠핑장. 아이들과 물놀이하기 좋습니다.",
    facilities: ["전기", "샤워장", "화장실", "물놀이장", "주차장"],
    tel: "031-000-0002",
    homepage: "https://www.gocamping.or.kr",
    type: "자동차야영장",
    region: "경기",
  },
  {
    id: "mock-3",
    name: "태안 솔밭 오토캠핑장",
    address: "충청남도 태안군 안면읍 솔밭길 78",
    lat: 36.5342,
    lng: 126.3358,
    image: "https://picsum.photos/seed/camp3/800/500",
    intro: "소나무 숲 사이 사이트. 해수욕장까지 도보 10분 거리입니다.",
    facilities: ["전기", "샤워장", "개수대", "편의점", "해변 접근"],
    tel: "041-000-0003",
    homepage: "https://www.gocamping.or.kr",
    type: "자동차야영장",
    region: "충남",
  },
  {
    id: "mock-4",
    name: "지리산 계곡 야영장",
    address: "전라남도 구례군 산동면 계곡로 12",
    lat: 35.2764,
    lng: 127.4617,
    image: "https://picsum.photos/seed/camp4/800/500",
    intro: "여름철 계곡 물놀이로 유명한 야영장. 그늘이 많아 한여름에도 시원합니다.",
    facilities: ["개수대", "화장실", "계곡물놀이", "주차장"],
    tel: "061-000-0004",
    homepage: "https://www.gocamping.or.kr",
    type: "일반야영장",
    region: "전남",
  },
  {
    id: "mock-5",
    name: "경주 보문 힐링캠핑장",
    address: "경상북도 경주시 보문로 234",
    lat: 35.8492,
    lng: 129.2986,
    image: "https://picsum.photos/seed/camp5/800/500",
    intro: "보문호수 산책로와 바로 연결되는 캠핑장. 글램핑 사이트도 함께 운영합니다.",
    facilities: ["전기", "온수 샤워장", "글램핑", "카페", "무선인터넷"],
    tel: "054-000-0005",
    homepage: "https://www.gocamping.or.kr",
    type: "글램핑",
    region: "경북",
  },
  {
    id: "mock-6",
    name: "제주 오름 캠핑장",
    address: "제주특별자치도 제주시 조천읍 오름로 56",
    lat: 33.5141,
    lng: 126.6294,
    image: "https://picsum.photos/seed/camp6/800/500",
    intro: "오름 전망을 감상할 수 있는 캠핑장. 일출/일몰 포인트로 인기가 많습니다.",
    facilities: ["전기", "샤워장", "개수대", "전망데크", "주차장"],
    tel: "064-000-0006",
    homepage: "https://www.gocamping.or.kr",
    type: "일반야영장",
    region: "제주",
  },
  {
    id: "mock-7",
    name: "정선 레일캠핑장",
    address: "강원특별자치도 정선군 정선읍 레일로 9",
    lat: 37.3806,
    lng: 128.6608,
    image: "https://picsum.photos/seed/camp7/800/500",
    intro: "폐선로를 개조한 독특한 컨셉의 캠핑장. 레일바이크와 함께 즐기기 좋습니다.",
    facilities: ["전기", "화장실", "개수대", "포토존"],
    tel: "033-000-0007",
    homepage: "https://www.gocamping.or.kr",
    type: "일반야영장",
    region: "강원",
  },
  {
    id: "mock-8",
    name: "부여 백제 캠핑장",
    address: "충청남도 부여군 규암면 백제로 88",
    lat: 36.2758,
    lng: 126.9019,
    image: "https://picsum.photos/seed/camp8/800/500",
    intro: "백마강을 조망할 수 있는 조용한 캠핑장. 역사 유적지와 가까워 가족 여행에 좋습니다.",
    facilities: ["전기", "샤워장", "화장실", "산책로"],
    tel: "041-000-0008",
    homepage: "https://www.gocamping.or.kr",
    type: "자동차야영장",
    region: "충남",
  },
];
